// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'TrackActionsCell': string;
  'downloadLink': string;
  'downloadLinkIcon': string;
  'downloadLinks': string;
}
export const cssExports: CssExports;
export default cssExports;
