// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'autoScroll': string;
  'both': string;
  'horizontal': string;
  'none': string;
  'scroller': string;
  'thumb': string;
  'track': string;
  'vertical': string;
}
export const cssExports: CssExports;
export default cssExports;
